<?php
/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the installation.
 * You don't have to use the web site, you can copy this file to "wp-config.php"
 * and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * Database settings
 * * Secret keys
 * * Database table prefix
 * * Localized language
 * * ABSPATH
 *
 * @link https://wordpress.org/support/article/editing-wp-config-php/
 *
 * @package WordPress
 */

// ** Database settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define( 'DB_NAME', 'db3XxLRTqoP0' );

/** Database username */
define( 'DB_USER', 'VK5V1x2j0H' );

/** Database password */
define( 'DB_PASSWORD', 'iKubrKLxy3' );

/** Database hostname */
define( 'DB_HOST', 'localhost' );

/** Database charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The database collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication unique keys and salts.
 *
 * Change these to different unique phrases! You can generate these using
 * the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}.
 *
 * You can change these at any point in time to invalidate all existing cookies.
 * This will force all users to have to log in again.
 *
 * @since 2.6.0
 */


/**#@-*/

/**
 * WordPress database table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'wp_';


/* Add any custom values between this line and the "stop editing" line. */

/*
 * IMPORTANT
 * THIS IS NOT A STANDARD WP-CONFIG FILE
 * CHANGES SHOULD GO IN my-config.php
 * /var/www/vhosts/gregmarshallracing.com/httpdocs/my-config.php
 * DO NOT EDIT THIS FILE, IT WILL BE OVERRIDEN
 * https://www.34sp.com/kb/128/wordpress-hosting-file-structure
 *
 */

define('AUTH_KEY',         '15c43f3aa676265cd2b8aa915c2181d9');
define('SECURE_AUTH_KEY',  'c6d3644d5cb902326e7b3a2c3c9a7ad1');
define('LOGGED_IN_KEY',    'b8e3851f8467b2f2397111cd6464faf2');
define('NONCE_KEY',        'a4afac4f248be0771b37ac4bf2acb9b9');
define('AUTH_SALT',        '2774935bc278b038d0bffbf2866d9298');
define('SECURE_AUTH_SALT', '6610f3e3d9f52189f99c52c2d74289d0');
define('LOGGED_IN_SALT',   'e853e29b74d977cce48b425cdca02b3f');
define('NONCE_SALT',       '8223b63f283221008dfb69e2cc7d1b51');

define('WP_CACHE', true);
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    define('FORCE_SSL_ADMIN', true);
    $_SERVER['HTTPS'] = 'on';
}
//Disable WordPress trying to update itself
define( 'WP_AUTO_UPDATE_CORE', false );

define('FS_METHOD', 'direct');
define('WP_CONTENT_DIR', '/var/www/vhosts/gregmarshallracing.com/httpdocs/wp-content');
define('WP_CACHE_KEY_SALT', '1077cc0a5742d056982e5f4715fc2d01');

//Define 34SP environment for plugin use
define('34SP_WPH', true);
//Set myconfig.php file
require_once('/var/www/vhosts/gregmarshallracing.com/httpdocs/my-config.php');

//Set the WP CONTENT URL
if (isset($_SERVER['HTTP_HOST']) && !defined('WP_CONTENT_URL'))  {
   $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https' : 'http';
  define('WP_CONTENT_URL', "{$protocol}://{$_SERVER['HTTP_HOST']}/wp-content");
}

//Specify options we disable by default but can be enabled.
if(!defined('DISABLE_WP_CRON')) {
    define('DISABLE_WP_CRON', true);
}
if(!defined('DISALLOW_FILE_EDIT')) {
    define( 'DISALLOW_FILE_EDIT', true);
}

if (isset($_SERVER['HTTP_HOST']) && $_SERVER['HTTP_HOST'] == 'gregmarshallracing.com.temp.link') {
    define('TFSP_TEMP_URL', 'gregmarshallracing.com.temp.link');
    if(!defined('WP_SITEURL')) {
      define('WP_SITEURL', "http://{$_SERVER['HTTP_HOST']}/");
    }
    if(!defined('WP_HOME')) {
      define('WP_HOME', "http://{$_SERVER['HTTP_HOST']}");
    }
}

// Disable WordPress Automatic Updater.
define('AUTOMATIC_UPDATER_DISABLED', true);


/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 *
 * For information on other constants that can be used for debugging,
 * visit the documentation.
 *
 * @link https://wordpress.org/support/article/debugging-in-wordpress/
 */
if ( ! defined( 'WP_DEBUG' ) ) {
	define( 'WP_DEBUG', false );
}

/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
